version: '3.1'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis: 
    container_name: redis
    build: 
      context: ./docker
      dockerfile: Redis.Dockerfile
  node:
    container_name: node
    build:
      context: ./
      dockerfile: node.Dockerfile
    command: yarn start:dev
    volumes:
      - ./src:/usr/src/app/src/
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - NODE_ENV=dev
    
  nginx:
    container_name: nginx
    build:
      context: docker
      dockerfile: nginx.Dockerfile
    ports:
      - 127:0:0:1:${NGINX_PORT}:80
    
      