version: '3.1'

services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    extends:
      file: docker-compose.yml
      service: redis
  adminer:
    extends:
      file: docker-compose.yml
      service: adminer
  node:
    extends:
      file: docker-compose.yml
      service: node
    depends_on:
      - db
      - redis
    command: yarn start:prod
    environment:
      - NODE_ENV=prod
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx    
    depends_on:
      - node
volumes:
  data: